<?php if ($totalSearchIndexes || $totalSearchPages || $totalSolrMappings): ?>
<h4><?php echo $this->translate('WARNING'); ?></h4>
<p><?php
echo sprintf($this->translate('This will delete all search indexes (%d), all search pages (%d), and all Solr mappings (%d) that use this Solr node.'),
    $totalSearchIndexes, $totalSearchPages, $totalSolrMappings);
?></p>
<p><?php
echo sprintf($this->translate('To keep search indexes and pages, create a new node and set it for the related indexes before deletion.'),
    $totalSearchIndexes, $totalSearchPages, $totalSolrMappings);
?></p>
<?php else: ?>
<p><?php
echo $this->translate('There is no search indexes, search pages, neither Solr mappings associated with this Solr node.');
?></p>
<?php endif; ?>
