<?php
$translate = $this->plugin('translate');
?>
<?php if ($totalSearchPages): ?>
<p><?php
echo sprintf($translate('Mapping between property "%s" and Solr field "%s" for "%s"'), $resource->source(), $resource->fieldName(), $resource->resourceName());
?></p>
<h4><?php echo $translate('WARNING'); ?></h4>
<p><?php
echo sprintf($translate('This will remove all references to this Solr mapping in search pages that use it (%d, of which %d enabled it for facets or sort fields).'),
    $totalSearchPages, $totalSearchPagesUsingMapping);
?></p>
<?php else: ?>
<p><?php
echo $translate('There is no search pages associated with this Solr mapping.');
?></p>
<?php endif; ?>
