<?php
/**
 * @var \Zend\View\Renderer\PhpRenderer $this
 * @var int $totalSearchPages
 * @var int $totalSearchIndexes
 * @var int $totalSolrMaps
 */

$translate = $this->plugin('translate');
?>
<?php if ($totalSearchIndexes || $totalSearchPages || $totalSolrMaps): ?>
<h4><?php echo $translate('WARNING'); ?></h4>
<p><?php
echo sprintf($translate('This will delete all search indexes (%d), all search pages (%d), and all Solr maps (%d) that use this Solr core.'),
    $totalSearchIndexes, $totalSearchPages, $totalSolrMaps);
?></p>
<p><?php
echo sprintf($translate('To keep search indexes and pages, create a new core and set it for the related indexes before deletion.'),
    $totalSearchIndexes, $totalSearchPages, $totalSolrMaps);
?></p>
<?php else: ?>
<p><?php
echo $translate('There is no search indexes, search pages, neither Solr maps associated with this Solr core.');
?></p>
<?php endif; ?>
