<?php
/**
 * @var \Zend\View\Renderer\PhpRenderer $this
 * @var \SearchSolr\Api\Representation\SolrMapRepresentation $resource
 * @var \SearchSolr\Api\Representation\SolrMapRepresentation $map
 * @var int $totalSearchPages
 * @var int $totalSearchPagesUsingMap
 */

$translate = $this->plugin('translate');
?>

<?php if ($totalSearchPages): ?>
<p>
    <?= sprintf($translate('Map between property "%s" and Solr field "%s" for "%s"'), $resource->source(), $resource->fieldName(), $resource->resourceName()) ?>
</p>
<h4><?= $translate('WARNING') ?></h4>
<p>
    <?= sprintf($translate('This will remove all references to this Solr map in search pages that use it (%d, of which %d are enabled for facets or sort fields).'),
        $totalSearchPages, $totalSearchPagesUsingMap) ?>
</p>
<?php else: ?>
<p>
    <?= $translate('There is no search pages associated with this Solr map.') ?>
</p>
<?php endif; ?>
