<?php
/*
 * Copyright BibLibre, 2016
 * Copyright Daniel Berthereau, 2017-2018
 *
 * This software is governed by the CeCILL license under French law and abiding
 * by the rules of distribution of free software.  You can use, modify and/ or
 * redistribute the software under the terms of the CeCILL license as circulated
 * by CEA, CNRS and INRIA at the following URL "http://www.cecill.info".
 *
 * As a counterpart to the access to the source code and rights to copy, modify
 * and redistribute granted by the license, users are provided only with a
 * limited warranty and the software's author, the holder of the economic
 * rights, and the successive licensors have only limited liability.
 *
 * In this respect, the user's attention is drawn to the risks associated with
 * loading, using, modifying and/or developing or reproducing the software by
 * the user in light of its specific status of free software, that may mean that
 * it is complicated to manipulate, and that also therefore means that it is
 * reserved for developers and experienced professionals having in-depth
 * computer knowledge. Users are therefore encouraged to load and test the
 * software's suitability as regards their requirements in conditions enabling
 * the security of their systems and/or data to be ensured and, more generally,
 * to use and operate it in the same conditions as regards security.
 *
 * The fact that you are presently reading this means that you have had
 * knowledge of the CeCILL license and that you accept its terms.
 */
?>

<?php
/**
 * @var \Zend\View\Renderer\PhpRenderer $this
 * @var \Solr\Api\Representation\SolrNodeRepresentation $nodes
 */

$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
?>
<?php $this->htmlElement('body')->appendAttribute('class', 'solr-node browse'); ?>

<?php echo $this->pageTitle($translate('Solr configuration')); ?>

<div id="page-actions">
    <a class="button" href="<?php echo $this->url('admin/solr/node', ['action' => 'add']); ?>"><?php echo $translate('Add new node'); ?></a>
</div>

<nav class="breadcrumbs">
    <?php
    echo $this->hyperlink($translate('Search'), $this->url('admin/search'));
    ?>
    <span><?php echo $translate('Solr nodes'); ?></span>
</nav>
<h2><?php echo $translate('Nodes'); ?></h2>
<?php if (count($nodes)): ?>
    <table class="tablesaw" data-tablesaw-mode="stack">
        <thead>
            <tr>
                <th><?php echo $translate('Name'); ?></th>
                <th><?php echo $translate('URL'); ?></th>
                <th><?php echo $translate('Status'); ?></th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($nodes as $node): ?>
                <tr>
                    <td>
                        <span><?php echo $node->name(); ?></span>
                        <ul class="actions">
                            <li><?php
                            $clientSettings = $node->clientSettings();
                            echo $this->hyperlink('',
                                sprintf('//%s:%s/solr/#/%s', $clientSettings['hostname'], $clientSettings['port'], substr($clientSettings['path'], 5)),
                                ['target' => '_blank', 'class' => 'o-icon-external', 'title' => $translate('Solr admin interface, if reachable'),]
                            );
                            ?></li>
                            <li>
                                <?php
                                    echo $node->link('', 'edit', [
                                        'class' => 'o-icon-edit',
                                        'title' => $translate('Edit'),
                                    ]);
                                ?>
                            </li>
                            <li>
                                <?php
                                    $href = $node->mappingUrl();
                                    echo $this->hyperlink('', $href, [
                                        'class' => 'o-icon- fa fa-sliders fa-sliders-h',
                                        'title' => $translate('Mapping'),
                                    ]);
                                ?>
                            </li>
                            <li>
                                <a href="#"
                                data-sidebar-content-url="<?php echo $escape($node->url('delete-confirm')); ?>"
                                class="o-icon-delete sidebar-content"
                                aria-label="<?php echo $escape($translate('Delete')); ?>"
                                title="<?php echo $escape($translate('Delete')); ?>"></a>
                            </li>
                        </ul>
                    </td>
                    <td><?php echo $node->clientUrl(); ?></td>
                    <td><?php echo $node->status(); ?></td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
<?php endif; ?>

<div class="sidebar">
    <a href="#"
        class="sidebar-close o-icon-close"
        aria-label="<?php echo $escape($translate('Close')); ?>"
        title="<?php echo $escape($translate('Close')); ?>"></a>
    <div class="sidebar-content"></div>
</div>
