<?php
/*
 * Copyright BibLibre, 2017
 * Copyright Daniel Berthereau, 2017-2018
 *
 * This software is governed by the CeCILL license under French law and abiding
 * by the rules of distribution of free software.  You can use, modify and/ or
 * redistribute the software under the terms of the CeCILL license as circulated
 * by CEA, CNRS and INRIA at the following URL "http://www.cecill.info".
 *
 * As a counterpart to the access to the source code and rights to copy, modify
 * and redistribute granted by the license, users are provided only with a
 * limited warranty and the software's author, the holder of the economic
 * rights, and the successive licensors have only limited liability.
 *
 * In this respect, the user's attention is drawn to the risks associated with
 * loading, using, modifying and/or developing or reproducing the software by
 * the user in light of its specific status of free software, that may mean that
 * it is complicated to manipulate, and that also therefore means that it is
 * reserved for developers and experienced professionals having in-depth
 * computer knowledge. Users are therefore encouraged to load and test the
 * software's suitability as regards their requirements in conditions enabling
 * the security of their systems and/or data to be ensured and, more generally,
 * to use and operate it in the same conditions as regards security.
 *
 * The fact that you are presently reading this means that you have had
 * knowledge of the CeCILL license and that you accept its terms.
 */
?>

<?php
/**
 * @var \Zend\View\Renderer\PhpRenderer $this
 * @var \Solr\Api\Representation\SolrNodeRepresentation $solrNode
 * @var \Solr\Form\Admin\SolrMappingForm $form
 */

$translate = $this->plugin('translate');
$this->htmlElement('body')->appendAttribute('class', 'solr-mapping create');
?>
<?php echo $this->pageTitle($translate('Add Solr mapping')); ?>
<nav class="breadcrumbs">
    <?php
    echo $this->hyperlink($translate('Search'), $this->url('admin/search'));
    echo $this->hyperlink($translate('Solr nodes'), $this->url('admin/solr'));
    echo $this->hyperlink(sprintf($translate('Resources list for node "%s"'), $solrNode->name()), $this->url('admin/solr/node-id-mapping', ['nodeId' => $solrNode->id()], true));
    echo $this->hyperlink(sprintf($translate('Mappings for "%s"'), $form->getOption('resource_name')), $this->url('admin/solr/node-id-mapping-resource', ['nodeId' => $solrNode->id(), 'resourceName' => $form->getOption('resource_name'), 'action' => 'browseResource'], true));
    ?>
    <span><?php echo $translate('Add'); ?></span>
</nav>
<?php echo $this->partial('solr/admin/mapping/form'); ?>
