<?php
/*
 * Copyright BibLibre, 2017
 * Copyright Daniel Berthereau, 2017-2018
 *
 * This software is governed by the CeCILL license under French law and abiding
 * by the rules of distribution of free software.  You can use, modify and/ or
 * redistribute the software under the terms of the CeCILL license as circulated
 * by CEA, CNRS and INRIA at the following URL "http://www.cecill.info".
 *
 * As a counterpart to the access to the source code and rights to copy, modify
 * and redistribute granted by the license, users are provided only with a
 * limited warranty and the software's author, the holder of the economic
 * rights, and the successive licensors have only limited liability.
 *
 * In this respect, the user's attention is drawn to the risks associated with
 * loading, using, modifying and/or developing or reproducing the software by
 * the user in light of its specific status of free software, that may mean that
 * it is complicated to manipulate, and that also therefore means that it is
 * reserved for developers and experienced professionals having in-depth
 * computer knowledge. Users are therefore encouraged to load and test the
 * software's suitability as regards their requirements in conditions enabling
 * the security of their systems and/or data to be ensured and, more generally,
 * to use and operate it in the same conditions as regards security.
 *
 * The fact that you are presently reading this means that you have had
 * knowledge of the CeCILL license and that you accept its terms.
 */
?>

<?php
/**
 * @var \Zend\View\Renderer\PhpRenderer $this
 * @var \Solr\Api\Representation\SolrNodeRepresentation $solrNode
 * @var \Solr\Api\Representation\SolrMappingRepresentation[] $mappings
 * @var string $resourceName
 */

$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
?>
<?php $this->htmlElement('body')->appendAttribute('class', 'solr-mapping browse'); ?>

<?php echo $this->pageTitle(sprintf($translate('Solr mappings for "%s"'), $resourceName)); ?>

<div id="page-actions">
    <?php $addUrl = $this->url('admin/solr/node-id-mapping-resource', [
        'nodeId' => $solrNode->id(),
        'resourceName' => $resourceName,
        'action' => 'add',
    ]); ?>
    <a class="button" href="<?php echo $addUrl ;?>"><?php echo $translate('Add new mapping'); ?></a>
    <?php $completeUrl = $this->url('admin/solr/node-id-mapping-resource', [
        'nodeId' => $solrNode->id(),
        'resourceName' => $resourceName,
        'action' => 'complete',
    ]); ?>
    <a class="button" href="<?php echo $completeUrl; ?>" title="<?php echo $translate('Add a text index to all missing and used properties.'); ?>"><?php echo $translate('Map all used properties'); ?></a>
    <?php $cleanUrl = $this->url('admin/solr/node-id-mapping-resource', [
        'nodeId' => $solrNode->id(),
        'resourceName' => $resourceName,
        'action' => 'clean',
    ]); ?>
    <a class="button" href="<?php echo $cleanUrl; ?>" title="<?php echo $translate('Remove mappings of properties that are not used.'); ?>"><?php echo $translate('Remove unused properties'); ?></a>
</div>

<nav class="breadcrumbs">
    <?php
    echo $this->hyperlink($translate('Solr nodes'), $this->url('admin/solr'));
    echo $this->hyperlink(sprintf($translate('Resources list for node "%s"'), $solrNode->name()), $this->url('admin/solr/node-id-mapping', [], true));
    ?><span><?php
    echo sprintf($translate('Mappings for "%s"'), $resourceName);
    ?></span>
</nav>

<?php if (count($mappings)): ?>
    <table class="tablesaw" data-tablesaw-mode="stack">
        <thead>
            <tr>
                <th><?php echo $translate('Solr field'); ?></th>
                <th><?php echo $translate('Source'); ?></th>
                <th><?php echo $translate('Translated default label'); ?></th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($mappings as $mapping): ?>
                <?php $mappingSettings = $mapping->settings(); ?>
                <tr>
                    <td>
                        <span><?php echo $mapping->fieldName(); ?></span>
                        <ul class="actions">
                            <li>
                                <?php
                                    $href = $mapping->adminUrl('edit');
                                    echo $this->hyperlink('', $href, [
                                        'class' => 'o-icon-edit',
                                        'title' => $translate('Edit'),
                                    ]);
                                ?>
                            </li>
                            <li>
                                <a href="#"
                                data-sidebar-content-url="<?php echo $escape($mapping->url('delete-confirm')); ?>"
                                class="o-icon-delete sidebar-content"
                                aria-label="<?php echo $escape($translate('Delete')); ?>"
                                title="<?php echo $escape($translate('Delete')); ?>"></a>
                            </li>
                        </ul>
                    </td>
                    <td><?php echo $mapping->source(); ?></td>
                    <td><?php if (!empty($mappingSettings['label'])) echo $translate($mappingSettings['label']); ?></td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
<?php else: ?>
    <p>
        <?php echo $translate('There is no mappings defined yet.'); ?>
        <a href="<?php echo $escape($addUrl); ?>"><?php echo $translate('Add a new mapping'); ?></a>
    </p>
<?php endif; ?>

<div class="sidebar">
    <a href="#"
        class="sidebar-close o-icon-close"
        aria-label="<?php echo $escape($translate('Close')); ?>"
        title="<?php echo $escape($translate('Close')); ?>"></a>
    <div class="sidebar-content"></div>
</div>
