<?php
/*
 * Copyright BibLibre, 2017
 * Copyright Daniel Berthereau, 2017-2018
 *
 * This software is governed by the CeCILL license under French law and abiding
 * by the rules of distribution of free software.  You can use, modify and/ or
 * redistribute the software under the terms of the CeCILL license as circulated
 * by CEA, CNRS and INRIA at the following URL "http://www.cecill.info".
 *
 * As a counterpart to the access to the source code and rights to copy, modify
 * and redistribute granted by the license, users are provided only with a
 * limited warranty and the software's author, the holder of the economic
 * rights, and the successive licensors have only limited liability.
 *
 * In this respect, the user's attention is drawn to the risks associated with
 * loading, using, modifying and/or developing or reproducing the software by
 * the user in light of its specific status of free software, that may mean that
 * it is complicated to manipulate, and that also therefore means that it is
 * reserved for developers and experienced professionals having in-depth
 * computer knowledge. Users are therefore encouraged to load and test the
 * software's suitability as regards their requirements in conditions enabling
 * the security of their systems and/or data to be ensured and, more generally,
 * to use and operate it in the same conditions as regards security.
 *
 * The fact that you are presently reading this means that you have had
 * knowledge of the CeCILL license and that you accept its terms.
 */
?>

<?php
/**
 * @var \Zend\View\Renderer\PhpRenderer $this
 * @var \Solr\Api\Representation\SolrNodeRepresentation $solrNode
 * @var \Solr\ValueExtractor\ValueExtractorInterface[] $valueExtractors
 */

$translate = $this->plugin('translate');
?>
<?php $this->htmlElement('body')->appendAttribute('class', 'solr-mapping browse'); ?>

<?php
$pageTitle = sprintf($translate('Solr node "%s"'), $solrNode->name());
echo $this->pageTitle($pageTitle);
?>

<nav class="breadcrumbs">
    <?php echo $this->hyperlink($translate('Search'), $this->url('admin/search')); ?>
    <?php echo $this->hyperlink($translate('Solr nodes'), $this->url('admin/solr')); ?>
    <span>
    <?php echo sprintf($translate('Resources list for node "%s"'), $solrNode->name()); ?>
    </span>
</nav>

<?php if (count($valueExtractors)): ?>
    <table class="tablesaw" data-tablesaw-mode="stack">
        <thead>
            <tr>
                <th><?php echo $translate('Name'); ?></th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($valueExtractors as $name => $valueExtractor): ?>
                <tr>
                    <td>
                        <span><?php echo $valueExtractor->getLabel(); ?></span>
                        <ul class="actions">
                            <li>
                                <?php
                                    $href = $this->url('admin/solr/node-id-mapping-resource', ['resourceName' => $name, 'nodeId' => $solrNode->id()]);
                                    echo $this->hyperlink('', $href, [
                                        'class' => 'o-icon-settings',
                                        'title' => $translate('Rules'),
                                    ]);
                                ?>
                            </li>
                        </ul>
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
<?php endif; ?>
