<?php
$this->headLink()->appendStylesheet($this->assetUrl('css/solr-admin.css', 'Solr'));
$this->headScript()->appendScript(
'var schema = ' . json_encode($schema) . ';
var sourceLabels = ' . json_encode($sourceLabels) . ';'
);
$this->headScript()->appendFile($this->assetUrl('js/solr-admin.js', 'Solr'));
?>

<?php $form->prepare(); ?>
<?php echo $this->form()->openTag($form); ?>
<div id="page-actions">
    <button><?php echo $this->translate('Save'); ?></button>
</div>
<?php echo $this->formCollection($form, false); ?>
<?php $this->trigger('view.add.form.after'); ?>
<?php echo $this->form()->closeTag(); ?>

<?php $this->trigger('view.add.after'); ?>
