<?php
/*
 * Copyright BibLibre, 2016
 * Copyright Daniel Berthereau, 2017-2023
 *
 * This software is governed by the CeCILL license under French law and abiding
 * by the rules of distribution of free software.  You can use, modify and/ or
 * redistribute the software under the terms of the CeCILL license as circulated
 * by CEA, CNRS and INRIA at the following URL "http://www.cecill.info".
 *
 * As a counterpart to the access to the source code and rights to copy, modify
 * and redistribute granted by the license, users are provided only with a
 * limited warranty and the software's author, the holder of the economic
 * rights, and the successive licensors have only limited liability.
 *
 * In this respect, the user's attention is drawn to the risks associated with
 * loading, using, modifying and/or developing or reproducing the software by
 * the user in light of its specific status of free software, that may mean that
 * it is complicated to manipulate, and that also therefore means that it is
 * reserved for developers and experienced professionals having in-depth
 * computer knowledge. Users are therefore encouraged to load and test the
 * software's suitability as regards their requirements in conditions enabling
 * the security of their systems and/or data to be ensured and, more generally,
 * to use and operate it in the same conditions as regards security.
 *
 * The fact that you are presently reading this means that you have had
 * knowledge of the CeCILL license and that you accept its terms.
 */

/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \SearchSolr\Api\Representation\SolrCoreRepresentation $cores
 */

$plugins = $this->getHelperPluginManager();
$translate = $plugins->get('translate');
$escape = $plugins->get('escapeHtml');

$this->headLink()->appendStylesheet($this->assetUrl('css/search-solr-admin.css', 'SearchSolr'));
?>

<?php $this->htmlElement('body')->appendAttribute('class', 'solr-core browse'); ?>

<?= $this->pageTitle($translate('Solr configuration')) ?>

<div id="page-actions">
    <a class="button" href="<?= $this->url('admin/search/solr/core', ['action' => 'add']) ?>"><?= $translate('Add new core') ?></a>
</div>

<nav class="breadcrumbs">
    <?php
    echo $this->hyperlink($translate('Search'), $this->url('admin/search'));
    ?>
    <span><?= $translate('Solr cores') ?></span>
</nav>

<?= $this->partial('search-solr/admin/core/browse-table') ?>

<div class="sidebar">
    <a href="#"
        class="sidebar-close o-icon-close"
        aria-label="<?= $escape($translate('Close')) ?>"
        title="<?= $escape($translate('Close')) ?>"></a>
    <div class="sidebar-content"></div>
</div>
