<?php
/*
 * Copyright BibLibre, 2016
 * Copyright Daniel Berthereau, 2017-2025
 *
 * This software is governed by the CeCILL license under French law and abiding
 * by the rules of distribution of free software.  You can use, modify and/ or
 * redistribute the software under the terms of the CeCILL license as circulated
 * by CEA, CNRS and INRIA at the following URL "http://www.cecill.info".
 *
 * As a counterpart to the access to the source code and rights to copy, modify
 * and redistribute granted by the license, users are provided only with a
 * limited warranty and the software's author, the holder of the economic
 * rights, and the successive licensors have only limited liability.
 *
 * In this respect, the user's attention is drawn to the risks associated with
 * loading, using, modifying and/or developing or reproducing the software by
 * the user in light of its specific status of free software, that may mean that
 * it is complicated to manipulate, and that also therefore means that it is
 * reserved for developers and experienced professionals having in-depth
 * computer knowledge. Users are therefore encouraged to load and test the
 * software's suitability as regards their requirements in conditions enabling
 * the security of their systems and/or data to be ensured and, more generally,
 * to use and operate it in the same conditions as regards security.
 *
 * The fact that you are presently reading this means that you have had
 * knowledge of the CeCILL license and that you accept its terms.
 */

/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \SearchSolr\Api\Representation\SolrCoreRepresentation $solrCores
 */

$plugins = $this->getHelperPluginManager();
$translate = $plugins->get('translate');
$escape = $plugins->get('escapeHtml');
?>

<h3 id="table-cores-caption"><?= $translate('Solr cores') ?></h3>

<?php if (count($solrCores)): ?>
<table aria-labelledby="table-cores-caption" class="tablesaw" data-tablesaw-mode="stack">
    <thead>
        <tr>
            <th><?= $translate('Name') ?></th>
            <th><?= $translate('URL') ?></th>
            <th><?= $translate('Status') ?></th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($solrCores as $solrCore): ?>
            <?php $status = $solrCore->status(); ?>
            <tr>
                <td>
                    <span><?= $solrCore->name() ?></span>
                    <ul class="actions">
                        <li>
                            <?= $this->hyperlink('',
                                $solrCore->clientUrlAdminBoard(),
                                ['target' => '_blank', 'class' => 'o-icon-external', 'title' => $translate('Solr admin interface, if reachable')]
                            ) ?>
                        </li>
                        <li>
                            <?= $solrCore->link('', 'edit', [
                                'class' => 'o-icon-edit',
                                'title' => $translate('Edit'),
                            ]) ?>
                        </li>
                        <li>
                        	<?php if ($status): ?>
                                <?= $this->hyperlink('', $solrCore->adminUrl(), [
                                    'class' => 'o-icon- far fa-sun',
                                    'title' => $translate('Get info about the Solr core and map Omeka metadata and Solr indices'), // @translate
                                ]) ?>
                            <?php else: ?>
	                            <span
                                    class="o-icon- far fa-sun disabled"
                                    aria-label="<?= $escape($translate('Get info about the Solr core and map Omeka metadata and Solr indices')) ?>"
                                    title="<?= $escape($translate('Get info about the Solr core and map Omeka metadata and Solr indices')) ?>"></span>
                            <?php endif; ?>
                        </li>
                        <li>
                            <a href="#"
                            data-sidebar-content-url="<?= $escape($solrCore->url('delete-confirm')) ?>"
                            class="o-icon-delete sidebar-content"
                            aria-label="<?= $escape($translate('Delete')) ?>"
                            title="<?= $escape($translate('Delete')) ?>"></a>
                        </li>
                    </ul>
                </td>
                <td><?= $solrCore->clientUrlAdmin() ?></td>
                <td><?= $solrCore->status(true) ?></td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>
<?php endif; ?>
