<?php
/*
 * Copyright BibLibre, 2016
 * Copyright Daniel Berthereau, 2017-2020
 *
 * This software is governed by the CeCILL license under French law and abiding
 * by the rules of distribution of free software.  You can use, modify and/ or
 * redistribute the software under the terms of the CeCILL license as circulated
 * by CEA, CNRS and INRIA at the following URL "http://www.cecill.info".
 *
 * As a counterpart to the access to the source code and rights to copy, modify
 * and redistribute granted by the license, users are provided only with a
 * limited warranty and the software's author, the holder of the economic
 * rights, and the successive licensors have only limited liability.
 *
 * In this respect, the user's attention is drawn to the risks associated with
 * loading, using, modifying and/or developing or reproducing the software by
 * the user in light of its specific status of free software, that may mean that
 * it is complicated to manipulate, and that also therefore means that it is
 * reserved for developers and experienced professionals having in-depth
 * computer knowledge. Users are therefore encouraged to load and test the
 * software's suitability as regards their requirements in conditions enabling
 * the security of their systems and/or data to be ensured and, more generally,
 * to use and operate it in the same conditions as regards security.
 *
 * The fact that you are presently reading this means that you have had
 * knowledge of the CeCILL license and that you accept its terms.
 */
?>

<?php
/**
 * @var \Zend\View\Renderer\PhpRenderer $this
 * @var \SearchSolr\Api\Representation\SolrCoreRepresentation $cores
 */

$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
?>
<?php $this->htmlElement('body')->appendAttribute('class', 'solr-core browse'); ?>

<?php echo $this->pageTitle($translate('Solr configuration')); ?>

<div id="page-actions">
    <a class="button" href="<?php echo $this->url('admin/solr/core', ['action' => 'add']); ?>"><?php echo $translate('Add new core'); ?></a>
</div>

<nav class="breadcrumbs">
    <?php
    echo $this->hyperlink($translate('Search'), $this->url('admin/search'));
    ?>
    <span><?php echo $translate('Solr cores'); ?></span>
</nav>
<h2><?php echo $translate('Cores'); ?></h2>
<?php if (count($cores)): ?>
    <table class="tablesaw" data-tablesaw-mode="stack">
        <thead>
            <tr>
                <th><?php echo $translate('Name'); ?></th>
                <th><?php echo $translate('URL'); ?></th>
                <th><?php echo $translate('Status'); ?></th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($cores as $core): ?>
                <tr>
                    <td>
                        <span><?php echo $core->name(); ?></span>
                        <ul class="actions">
                            <li><?php
                            echo $this->hyperlink('',
                                $core->clientUrlAdminBoard(),
                                ['target' => '_blank', 'class' => 'o-icon-external', 'title' => $translate('Solr admin interface, if reachable'),]
                            );
                            ?></li>
                            <li>
                                <?php
                                    echo $core->link('', 'edit', [
                                        'class' => 'o-icon-edit',
                                        'title' => $translate('Edit'),
                                    ]);
                                ?>
                            </li>
                            <li>
                                <?php
                                    $href = $core->mapUrl();
                                    echo $this->hyperlink('', $href, [
                                        'class' => 'o-icon- fa fa-sliders fa-sliders-h',
                                        'title' => $translate('Map'),
                                    ]);
                                ?>
                            </li>
                            <li>
                                <a href="#"
                                data-sidebar-content-url="<?php echo $escape($core->url('delete-confirm')); ?>"
                                class="o-icon-delete sidebar-content"
                                aria-label="<?php echo $escape($translate('Delete')); ?>"
                                title="<?php echo $escape($translate('Delete')); ?>"></a>
                            </li>
                        </ul>
                    </td>
                    <td><?php echo $core->clientUrlAdmin(); ?></td>
                    <td><?php echo $core->status(); ?></td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
<?php endif; ?>

<?php if (!class_exists('SolrDisMaxQuery')): ?>
<p>
<?php $solrVersion = class_exists('SolrUtils') ? \SolrUtils::getSolrVersion() : $translate('[unknown]'); ?>
<?php echo sprintf($translate('To use advanced query options, you need the php-solr library 2.1.0 or above (lastest recommended, current %s).'), $solrVersion); ?>
</p>
<?php endif; ?>

<div class="sidebar">
    <a href="#"
        class="sidebar-close o-icon-close"
        aria-label="<?php echo $escape($translate('Close')); ?>"
        title="<?php echo $escape($translate('Close')); ?>"></a>
    <div class="sidebar-content"></div>
</div>
