<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 */

$plugins = $this->getHelperPluginManager();
$escape = $plugins->get('escapeHtml');
$partial = $plugins->get('partial');
$translate = $plugins->get('translate');
?>

<details class="info quick-help">
    <summary><?= $escape($translate('About index names')) ?></summary>
    <?= $partial('search-solr/admin/core/help-index-names-content') ?>
</details>
