<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \SearchSolr\Api\Representation\SolrCoreRepresentation $solrCore
 * @var \SearchSolr\Form\Admin\SolrCoreMappingImportForm $form
 */

$plugins = $this->getHelperPluginManager();
$url = $plugins->get('url');
$translate = $plugins->get('translate');
$hyperlink = $plugins->get('hyperlink');

$form->prepare();
?>

<?= $this->pageTitle($translate('Import Solr core mapping')) ?>

<div id="page-actions">
    <?php $exportUrl = $url('admin/search/solr/core-id', [
        'id' => $solrCore->id(),
        'action' => 'export',
    ]); ?>
    <a class="button" href="<?= $exportUrl ?>" title="<?= $translate('Export maps for easier spreadsheet mapping.') ?>"><?= $translate('Export mapping') ?></a>
    <button type="submit" class="button" form="<?= $form->getAttribute('id') ?>"><?= $translate('Submit') ?></button>
</div>

<nav class="breadcrumbs" aria-label="<?= $translate('Breadcrumb') ?>">
    <?= $hyperlink($translate('Search'), $url('admin/search')) ?>
    <?= $hyperlink($translate('Solr cores'), $url('admin/search/solr')) ?>
    <span aria-current="page"><?= sprintf($translate('Import mapping for core "%s"'), $solrCore->name()) ?></span>
</nav>

<p>
    <?= $translate('Warning: To import a mapping will reset the current mapping for all resources of the core. It is recommended to export it first.') ?>
</p>

<p>
    <?= $translate('The form should be a spreadsheet with the same headers than the export ones.') ?>
</p>

<?= $this->form()->openTag($form) ?>
<?= $this->formCollection($form, false) ?>
<?= $this->form()->closeTag($form) ?>
