<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \SearchSolr\Api\Representation\SolrCoreRepresentation $solrCore
 * @var \SearchSolr\Form\Admin\SolrCoreMappingImportForm $form
 */

$plugins = $this->getHelperPluginManager();
$url = $plugins->get('url');
$assetUrl = $plugins->get('assetUrl');
$translate = $plugins->get('translate');
$hyperlink = $plugins->get('hyperlink');

$form->prepare();

$this->headLink()
    ->appendStylesheet($assetUrl('css/search-solr-admin.css', 'SearchSolr'));

$this->htmlElement('body')->appendAttribute('class', 'solr-cores import');
?>

<?= $this->pageTitle($translate('Import mapping'), 1, $translate('Solr core')) ?>

<div id="page-actions">
    <a class="button" href="<?= $solrCore->adminUrl('export') ?>" title="<?= $translate('Export maps for easier spreadsheet mapping.') ?>"><?= $translate('Export mapping') ?></a>
    <button type="submit" class="button" form="<?= $form->getAttribute('id') ?>"><?= $translate('Submit') ?></button>
</div>

<nav class="breadcrumbs" aria-label="<?= $translate('Breadcrumb') ?>">
    <?= $hyperlink($translate('Search'), $url('admin/search')) ?>
    <?= $hyperlink($translate('Solr cores'), $url('admin/search/solr')) ?>
    <?= $hyperlink($solrCore->name(), $solrCore->adminUrl()) ?>
    <span aria-current="page"><?= $translate('Import mapping') ?></span>
</nav>

<p>
    <?= $translate('Warning: To import a mapping will reset the current mapping for all resources of the core. It is recommended to export it first.') ?>
</p>

<p>
    <?= $translate('The form should be a spreadsheet with the same headers than the export ones.') ?>
</p>

<?= $this->form()->openTag($form) ?>
<?= $this->formCollection($form, false) ?>
<?= $this->form()->closeTag($form) ?>
