<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \SearchSolr\Api\Representation\SolrCoreRepresentation $solrCore
 * @var \AdvancedSearch\Api\Representation\SearchConfigRepresentation|null $searchConfig
 * @var string $fieldName
 * @var string $sort
 */

$plugins = $this->getHelperPluginManager();
$escape = $plugins->get('escapeHtml');
$translate = $plugins->get('translate');
$escapeAttr = $plugins->get('escapeHtmlAttr');

$listValues = $solrCore->queryValuesCount($fieldName, $sort);

$row = $translate('%1$s %2$s');

if ($searchConfig) {
    $baseUrlQuery = $searchConfig->adminSearchUrl(false, [$fieldName => '']);
}
?>

<h3><?= $escape($fieldName) ?></h3>

<div class="meta-group meta-group-list">
	<h4><?= sprintf($translate('Total indexed values: %d'), count($listValues)) ?></h4>
    <ul>
        <?php foreach ($listValues as $value => $count): ?>
        <li><?= $searchConfig
            ? sprintf($row, sprintf('<a href="%1$s" class="value-text">%2$s</a>', $escapeAttr($baseUrlQuery . rawurlencode($value)), $escape($value)), '<span class="value-count">' . $count . '</span>')
            : sprintf($row, sprintf('<span class="value-text">%s</span>', $escape($value)), '<span class="value-count">' . $count . '</span>')
            ?></li>
        <?php endforeach; ?>
    </ul>
</div>
