<?php
/*
 * Copyright BibLibre, 2017
 * Copyright Daniel Berthereau, 2017-2025
 *
 * This software is governed by the CeCILL license under French law and abiding
 * by the rules of distribution of free software.  You can use, modify and/ or
 * redistribute the software under the terms of the CeCILL license as circulated
 * by CEA, CNRS and INRIA at the following URL "http://www.cecill.info".
 *
 * As a counterpart to the access to the source code and rights to copy, modify
 * and redistribute granted by the license, users are provided only with a
 * limited warranty and the software's author, the holder of the economic
 * rights, and the successive licensors have only limited liability.
 *
 * In this respect, the user's attention is drawn to the risks associated with
 * loading, using, modifying and/or developing or reproducing the software by
 * the user in light of its specific status of free software, that may mean that
 * it is complicated to manipulate, and that also therefore means that it is
 * reserved for developers and experienced professionals having in-depth
 * computer knowledge. Users are therefore encouraged to load and test the
 * software's suitability as regards their requirements in conditions enabling
 * the security of their systems and/or data to be ensured and, more generally,
 * to use and operate it in the same conditions as regards security.
 *
 * The fact that you are presently reading this means that you have had
 * knowledge of the CeCILL license and that you accept its terms.
 */

/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \SearchSolr\Api\Representation\SolrCoreRepresentation $solrCore
 * @var \SearchSolr\ValueExtractor\ValueExtractorInterface[] $valueExtractors
 */

$plugins = $this->getHelperPluginManager();
$url = $plugins->get('url');
$assetUrl = $plugins->get('assetUrl');
$translate = $plugins->get('translate');
$hyperlink = $plugins->get('hyperlink');

$this->headLink()
    ->appendStylesheet($assetUrl('css/search-solr-admin.css', 'SearchSolr'));

$this->htmlElement('body')->appendAttribute('class', 'solr-cores solr-map browse');
?>

<?= $this->pageTitle($translate('Solr indices'), 1, $translate('Solr core')) ?>

<div id="page-actions">
    <?php if ($solrCore->userIsAllowed('update')): ?>
    <?= $hyperlink($translate('Import mapping'), $solrCore->adminUrl('import'), [
        'class' => 'button',
        'title' => $translate('Import maps. Warning: it will reset the current mapping for all resources. It is recommended to export it first.')]) ?>
    <?php endif; ?>
    <?= $hyperlink($translate('Export mapping'), $solrCore->adminUrl('export'), [
        'class' => 'button',
        'title' => $translate('Export maps for easier spreadsheet mapping.')]) ?>
</div>

<nav class="breadcrumbs">
    <?= $hyperlink($translate('Search'), $url('admin/search')) ?>
    <?= $hyperlink($translate('Solr cores'), $url('admin/search/solr')) ?>
    <?= $hyperlink($solrCore->name(), $solrCore->adminUrl()) ?>
    <span><?= $translate('Resource types') ?></span>
</nav>

<div class="by-resource-type">
<?php if (count($valueExtractors)): ?>
    <table class="tablesaw" data-tablesaw-mode="stack">
        <thead>
            <tr>
                <th><?= $translate('Name') ?></th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($valueExtractors as $name => $valueExtractor): ?>
                <tr>
                    <td>
                        <span><?= $valueExtractor->getLabel() ?></span>
                        <ul class="actions">
                            <li>
                                <?= $hyperlink(
                                    '',
                                    $url('admin/search/solr/core-id-map-resource', ['resourceName' => $name, 'coreId' => $solrCore->id()]),
                                    ['class' => 'o-icon-settings', 'title' => $translate('Rules')]
                                ) ?>
                            </li>
                        </ul>
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
<?php endif; ?>
</div>
