<?php
/*
 * Copyright BibLibre, 2017
 * Copyright Daniel Berthereau, 2017-2025
 *
 * This software is governed by the CeCILL license under French law and abiding
 * by the rules of distribution of free software.  You can use, modify and/ or
 * redistribute the software under the terms of the CeCILL license as circulated
 * by CEA, CNRS and INRIA at the following URL "http://www.cecill.info".
 *
 * As a counterpart to the access to the source code and rights to copy, modify
 * and redistribute granted by the license, users are provided only with a
 * limited warranty and the software's author, the holder of the economic
 * rights, and the successive licensors have only limited liability.
 *
 * In this respect, the user's attention is drawn to the risks associated with
 * loading, using, modifying and/or developing or reproducing the software by
 * the user in light of its specific status of free software, that may mean that
 * it is complicated to manipulate, and that also therefore means that it is
 * reserved for developers and experienced professionals having in-depth
 * computer knowledge. Users are therefore encouraged to load and test the
 * software's suitability as regards their requirements in conditions enabling
 * the security of their systems and/or data to be ensured and, more generally,
 * to use and operate it in the same conditions as regards security.
 *
 * The fact that you are presently reading this means that you have had
 * knowledge of the CeCILL license and that you accept its terms.
 */

/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \SearchSolr\Api\Representation\SolrCoreRepresentation $solrCore
 * @var \SearchSolr\ValueExtractor\ValueExtractorInterface[] $valueExtractors
 */

$plugins = $this->getHelperPluginManager();
$url = $plugins->get('url');
$escape = $plugins->get('escapeHtml');
$assetUrl = $plugins->get('assetUrl');
$translate = $plugins->get('translate');
$hyperlink = $plugins->get('hyperlink');

$this->headScript()->appendScript(
    'const schema = ' . json_encode($solrCore->schema()->getSchema(), JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE) . ';
const sourceLabels = ' . json_encode([], JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE) . ';'
);

$this->headLink()
    ->appendStylesheet($assetUrl('css/search-solr-admin.css', 'SearchSolr'));
$this->headScript()
    ->appendFile($assetUrl('js/search-solr-admin.js', 'SearchSolr'), 'text/javascript', ['defer' => 'defer']);

$this->htmlElement('body')->appendAttribute('class', 'solr-map browse');
?>

<?= $this->pageTitle(sprintf($translate('Solr core "%s"'), $solrCore->name())) ?>

<div id="page-actions">
    <?php $exportUrl = $url('admin/search/solr/core-id', [
        'id' => $solrCore->id(),
        'action' => 'export',
    ]); ?>
    <a class="button" href="<?= $exportUrl ?>" title="<?= $translate('Export maps for easier spreadsheet mapping.') ?>"><?= $translate('Export mapping') ?></a>
    <?php $exportUrl = $url('admin/search/solr/core-id', [
        'id' => $solrCore->id(),
        'action' => 'import',
    ]); ?>
    <a class="button" href="<?= $exportUrl ?>" title="<?= $translate('Import maps. Warning: it will reset the current mapping for all resources. It is recommended to export it first.') ?>"><?= $translate('Import mapping') ?></a>
</div>

<nav class="breadcrumbs">
    <?= $this->hyperlink($translate('Search'), $this->url('admin/search')) ?>
    <?= $this->hyperlink($translate('Solr cores'), $this->url('admin/search/solr')) ?>
    <span>
    <?= sprintf($translate('Indices for core "%s"'), $solrCore->name()) ?>
    </span>
</nav>

<h3><?= $translate('By resource type') ?></h3>

<div class="by-resource-type">
<?php if (count($valueExtractors)): ?>
    <table class="tablesaw" data-tablesaw-mode="stack">
        <thead>
            <tr>
                <th><?= $translate('Name') ?></th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($valueExtractors as $name => $valueExtractor): ?>
                <tr>
                    <td>
                        <span><?= $valueExtractor->getLabel() ?></span>
                        <ul class="actions">
                            <li>
                                <?= $hyperlink(
                                    '',
                                    $url('admin/search/solr/core-id-map-resource', ['resourceName' => $name, 'coreId' => $solrCore->id()]),
                                    ['class' => 'o-icon-settings', 'title' => $translate('Rules')]
                                ) ?>
                            </li>
                        </ul>
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
<?php endif; ?>
</div>

<h3><?= $translate('By index') ?></h3>

<div class="by-solr-index">
<?php $maps = $solrCore->mapsByFieldName(); ?>
<?php if (count($maps)): ?>
    <table class="tablesaw" data-tablesaw-mode="stack">
        <thead>
            <tr>
                <th><?= $translate('Name') ?></th>
                <th><?= $translate('Sources Omeka (with formatter)') ?></th>
            </tr>
        </thead>
        <tbody>
            <?php /** @var \SearchSolr\Api\Representation\SolrMapRepresentation[] $fieldMaps */ ?>
            <?php foreach ($maps as $fieldName => $fieldMaps): ?>
                <tr>
                    <td>
                        <span><?= $escape($fieldName) ?></span>
                        <ul class="actions">
                            <li>
                                <?= $hyperlink('', '#', [
                                    'data-sidebar-selector' => '#sidebar',
                                    'data-sidebar-content-url' => $solrCore->adminUrl('list-values') . '?fieldname=' . rawurlencode($fieldName),
                                    'class' => 'o-icon- fas fa-sort-alpha-down sidebar-content',
                                    'title' => $translate('List indexed values'),
                                ]) ?>
                            </li>
                        </ul>
                    </td>
                    <td>
                        <ul class="sources">
                            <?php foreach ($fieldMaps as $map):
                                $formatter = $map->setting('formatter');
                                ?>
                            <li><?= $formatter
                                ? $escape(sprintf($translate('%1$s [%2$s] (%3$s)'), $map->source(), $map->resourceName(), $map->setting('formatter') ?: $translate('[none]')))
                                : $escape(sprintf($translate('%1$s [%2$s]'), $map->source(), $map->resourceName()))
                            ?></li>
                        <?php endforeach; ?>
                        </ul>
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
<?php endif; ?>
</div>

<div id="sidebar" class="sidebar">
    <?= $hyperlink('', '#', ['class' => 'sidebar-close o-icon-close', 'title' => $translate('Close')]) ?>
    <div class="sidebar-content"></div>
</div>
