<?php
/*
 * Copyright BibLibre, 2017
 * Copyright Daniel Berthereau, 2017-2025
 *
 * This software is governed by the CeCILL license under French law and abiding
 * by the rules of distribution of free software.  You can use, modify and/ or
 * redistribute the software under the terms of the CeCILL license as circulated
 * by CEA, CNRS and INRIA at the following URL "http://www.cecill.info".
 *
 * As a counterpart to the access to the source code and rights to copy, modify
 * and redistribute granted by the license, users are provided only with a
 * limited warranty and the software's author, the holder of the economic
 * rights, and the successive licensors have only limited liability.
 *
 * In this respect, the user's attention is drawn to the risks associated with
 * loading, using, modifying and/or developing or reproducing the software by
 * the user in light of its specific status of free software, that may mean that
 * it is complicated to manipulate, and that also therefore means that it is
 * reserved for developers and experienced professionals having in-depth
 * computer knowledge. Users are therefore encouraged to load and test the
 * software's suitability as regards their requirements in conditions enabling
 * the security of their systems and/or data to be ensured and, more generally,
 * to use and operate it in the same conditions as regards security.
 *
 * The fact that you are presently reading this means that you have had
 * knowledge of the CeCILL license and that you accept its terms.
 */

/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \SearchSolr\Api\Representation\SolrCoreRepresentation $solrCore
 * @var \SearchSolr\Api\Representation\SolrMapRepresentation[] $maps
 * @var string $resourceName
 */

$plugins = $this->getHelperPluginManager();
$url = $plugins->get('url');
$assetUrl = $plugins->get('assetUrl');
$escape = $plugins->get('escapeHtml');
$translate = $plugins->get('translate');
$hyperlink = $plugins->get('hyperlink');
$escapeAttr = $plugins->get('escapeHtmlAttr');

$this->headLink()
    ->appendStylesheet($assetUrl('css/search-solr-admin.css', 'SearchSolr'));

$this->htmlElement('body')->appendAttribute('class', 'solr-cores solr-map browse');
?>

<?= $this->pageTitle($translate('Solr indices'), 1, $translate('Solr core')) ?>

<div id="page-actions">
    <?php $addUrl = $url('admin/search/solr/core-id-map-resource', [
        'core-id' => $solrCore->id(),
        'resource-name' => $resourceName,
        'action' => 'add',
    ]); ?>
    <a class="button" href="<?= $addUrl ?>"><?= $translate('Add new map') ?></a>
    <?php $completeUrl = $url('admin/search/solr/core-id-map-resource', [
        'core-id' => $solrCore->id(),
        'resource-name' => $resourceName,
        'action' => 'complete',
    ]); ?>
    <a class="button" href="<?= $completeUrl ?>" title="<?= $translate('Add a text index to all missing and used properties.') ?>"><?= $translate('Map all used properties') ?></a>
    <?php $cleanUrl = $url('admin/search/solr/core-id-map-resource', [
        'core-id' => $solrCore->id(),
        'resource-name' => $resourceName,
        'action' => 'clean',
    ]); ?>
    <a class="button" href="<?= $cleanUrl ?>" title="<?= $translate('Remove maps of properties that are not used.') ?>"><?= $translate('Remove unused properties') ?></a>
</div>

<nav class="breadcrumbs">
    <?= $hyperlink($translate('Search'), $url('admin/search')) ?>
    <?= $hyperlink($translate('Solr cores'), $url('admin/search/solr')) ?>
    <?= $hyperlink($solrCore->name(), $solrCore->adminUrl()) ?>
    <?= $hyperlink($translate('Resource types'), $solrCore->mapUrl()) ?>
    <span><?= sprintf($translate('Indices for "%s"'), $resourceName) ?></span>
</nav>

<?php if (count($maps)): ?>
    <?php // Adapted in core/show. ?>
    <table aria-label="<?= $escapeAttr($translate('Maps')) ?>" class="tablesaw" data-tablesaw-mode="stack">
        <thead>
            <tr>
                <th><?= $translate('Source Omeka') ?></th>
                <th><?= $translate('Pool / Filter') ?></th>
                <th><?= $translate('Index Solr') ?></th>
                <th><?= $translate('Format') ?></th>
                <?php // This is the default translated label. ?>
                <th><?= $translate('Label') ?></th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($maps as $map):
                $mapSettings = $map->settings();
                ?>
                <tr>
                    <td>
                        <span><?= $map->source() ?></span>
                        <div></div>
                        <ul class="actions">
                        <?php if ($map->resourceName() !== $resourceName): ?>
                            <li>
                                <span class="field-generic"><?= $map->resourceName() ?></span>
                            </li>
                        <?php endif; ?>
                            <li>
                                <?= $hyperlink('', $map->adminUrl('edit'), [
                                    'class' => 'o-icon-edit',
                                    'title' => $translate('Edit'),
                                ]) ?>
                            </li>
                            <li>
                                <a href="#"
                                data-sidebar-content-url="<?= $escape($map->url('delete-confirm')) ?>"
                                class="o-icon-delete sidebar-content"
                                aria-label="<?= $escape($translate('Delete')) ?>"
                                title="<?= $escape($translate('Delete')) ?>"></a>
                            </li>
                        </ul>
                    </td>
                    <td><?php
                        $filterValues = $map->pool('filter_values');
                        $filterUris = $map->pool('filter_uris');
                        $filterResources = $map->pool('filter_resources');
                        $filterValueResources = $map->pool('filter_value_resources');
                        $dataTypes = $map->pool('data_types');
                        $dataTypesExclude = $map->pool('data_types_exclude');
                        $filterLanguages = $map->pool('filter_languages');
                        $filterVisibility = $map->pool('filter_visibility');
                        ?>
                        <?php if ($filterValues): ?>
                        <div><?= $translate('Filtered by values') ?></div>
                        <?php endif; ?>
                        <?php if ($filterUris): ?>
                        <div><?= $translate('Filtered by uris') ?></div>
                        <?php endif; ?>
                        <?php if ($filterResources): ?>
                        <div><?= $translate('Filtered by resources') ?></div>
                        <?php endif; ?>
                        <?php if ($filterValueResources): ?>
                        <div><?= $translate('Filtered by value resources') ?></div>
                        <?php endif; ?>
                        <?php if ($dataTypes || $dataTypesExclude): ?>
                        <dl>
                            <?= $dataTypes ? '<dt>' . $translate('Data types') . '</dt><dd>' . implode('</dd><dd>', $dataTypes) . '</dd>' : '' ?>
                            <?= $dataTypesExclude ? '<dt>' . $translate('Excluded data types') . '</dt><dd>' . implode('</dd><dd>', $dataTypesExclude) . '</dd>' : '' ?>
                        </dl>
                        <?php endif; ?>
                        <?php if ($filterLanguages): ?>
                        <dl>
                            <dt><?= $translate('Only languages') ?></dt>
                            <dd><?= implode('</dd><dd>', $filterLanguages) ?></dd>
                        </dl>
                        <?php endif; ?>
                        <?php if ($filterVisibility === 'public'): ?>
                        <div><?= $translate('Filtered by visibility Public') ?></div>
                        <?php elseif ($filterVisibility === 'private'): ?>
                        <div><?= $translate('Filtered by visibility Private') ?></div>
                        <?php endif; ?>
                    </td>
                    <td><?= $map->fieldName() ?></td>
                    <td>
                        <?= $formatter = $mapSettings['formatter'] ?? '' ?>
                        <?= $formatter === 'table' ? $mapSettings['table'] ?? '' : '' ?>
                    </td>
                    <td><?= !empty($mapSettings['label']) ? $translate($mapSettings['label']) : '' ?></td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
<?php else: ?>
    <p>
        <?= $translate('There is no maps defined yet.') ?>
        <a href="<?= $escape($addUrl) ?>"><?= $translate('Add a new map') ?></a>
    </p>
<?php endif; ?>

<div class="sidebar">
    <a href="#"
        class="sidebar-close o-icon-close"
        aria-label="<?= $escape($translate('Close')) ?>"
        title="<?= $escape($translate('Close')) ?>"></a>
    <div class="sidebar-content"></div>
</div>
