<?php
/*
 * Copyright BibLibre, 2017
 * Copyright Daniel Berthereau, 2017-2025
 *
 * This software is governed by the CeCILL license under French law and abiding
 * by the rules of distribution of free software.  You can use, modify and/ or
 * redistribute the software under the terms of the CeCILL license as circulated
 * by CEA, CNRS and INRIA at the following URL "http://www.cecill.info".
 *
 * As a counterpart to the access to the source code and rights to copy, modify
 * and redistribute granted by the license, users are provided only with a
 * limited warranty and the software's author, the holder of the economic
 * rights, and the successive licensors have only limited liability.
 *
 * In this respect, the user's attention is drawn to the risks associated with
 * loading, using, modifying and/or developing or reproducing the software by
 * the user in light of its specific status of free software, that may mean that
 * it is complicated to manipulate, and that also therefore means that it is
 * reserved for developers and experienced professionals having in-depth
 * computer knowledge. Users are therefore encouraged to load and test the
 * software's suitability as regards their requirements in conditions enabling
 * the security of their systems and/or data to be ensured and, more generally,
 * to use and operate it in the same conditions as regards security.
 *
 * The fact that you are presently reading this means that you have had
 * knowledge of the CeCILL license and that you accept its terms.
 */

/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \SearchSolr\Api\Representation\SolrCoreRepresentation $solrCore
 * @var \SearchSolr\Api\Representation\SolrMapRepresentation $map
 * @var string $resourceName
 * @var \SearchSolr\Form\Admin\SolrMapForm $form
 * @var array $schema
 * @var array $sourceLabels
 */

$plugins = $this->getHelperPluginManager();
$url = $plugins->get('url');
$assetUrl = $plugins->get('assetUrl');
$translate = $plugins->get('translate');
$hyperlink = $plugins->get('hyperlink');

$this->headLink()
    ->appendStylesheet($assetUrl('css/search-solr-admin.css', 'SearchSolr'));

$this->htmlElement('body')->appendAttribute('class', 'solr-cores solr-map create edit');
?>

<?= $this->pageTitle($translate('Edit index'), 1, $translate('Solr core')) ?>

<nav class="breadcrumbs">
    <?= $hyperlink($translate('Search'), $url('admin/search')) ?>
    <?= $hyperlink($translate('Solr cores'), $url('admin/search/solr')) ?>
    <?= $hyperlink($solrCore->name(), $solrCore->adminUrl()) ?>
    <?= $hyperlink($translate('Indices'), $solrCore->resourceMapUrl($resourceName)) ?>
    <span><?= $translate('Edit') ?></span>
</nav>

<?= $this->partial('search-solr/admin/map/form') ?>
