<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \SearchSolr\Form\Admin\SolrMapForm $form
 * @var string $schema
 * @var array $sourceLabels
 */

$plugins = $this->getHelperPluginManager();
$assetUrl = $plugins->get('assetUrl');
$translate = $plugins->get('translate');

$this->headLink()
    ->appendStylesheet($assetUrl('css/search-solr-admin.css', 'SearchSolr'));
$this->headScript()
    ->appendScript(
    'const schema = ' . json_encode($schema, JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE) . ';
const sourceLabels = ' . json_encode($sourceLabels, JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE) . ';'
)
    ->appendFile($assetUrl('js/search-solr-admin-map.js', 'SearchSolr'), 'text/javascript', ['defer' => 'defer']);

$form->prepare();

/** @see \Common\Form\Element\DataTypeSelect */
// Temp fix for DataTypeSelect inside a fieldset.
$dataTypeManager = $this->api()->read('vocabularies', 1)->getContent()->getServiceLocator()->get('Omeka\DataTypeManager');
$form->remove('data_types');
$form->get('o:pool')->get('data_types')->setDataTypeManager($dataTypeManager);
$form->get('o:pool')->get('data_types_exclude')->setDataTypeManager($dataTypeManager);
?>

<?= $this->form()->openTag($form) ?>

<div id="page-actions">
    <?= $this->cancelButton() ?>
    <button type="submit" class="button"><?= $translate('Save') ?></button>
</div>

<h4><?= $translate('Source') ?></h4>
<p><?= $translate('Metadata to extract from Omeka') ?></p>
<?= $this->formRow($form->get('o:source')) ?>
<?= $this->formCollection($form->get('o:pool')) ?>

<h4><?= $translate('Destination') ?></h4>
<p><?= $translate('Index of metadata in Solr') ?></p>
<?= $this->formRow($form->get('o:field_name')) ?>

<h4><?= $translate('Format') ?></h4>
<p><?= $translate('Adapt the metadata') ?></p>
<?= $this->formCollection($form->get('o:settings')) ?>

<?= $this->formRow($form->get('csrf')) ?>

<?php $this->trigger('view.add.form.after'); ?>
<?= $this->form()->closeTag() ?>

<?php $this->trigger('view.add.after'); ?>
