<?php
/*
 * Copyright BibLibre, 2016
 *
 * This software is governed by the CeCILL license under French law and abiding
 * by the rules of distribution of free software.  You can use, modify and/ or
 * redistribute the software under the terms of the CeCILL license as circulated
 * by CEA, CNRS and INRIA at the following URL "http://www.cecill.info".
 *
 * As a counterpart to the access to the source code and rights to copy, modify
 * and redistribute granted by the license, users are provided only with a
 * limited warranty and the software's author, the holder of the economic
 * rights, and the successive licensors have only limited liability.
 *
 * In this respect, the user's attention is drawn to the risks associated with
 * loading, using, modifying and/or developing or reproducing the software by
 * the user in light of its specific status of free software, that may mean that
 * it is complicated to manipulate, and that also therefore means that it is
 * reserved for developers and experienced professionals having in-depth
 * computer knowledge. Users are therefore encouraged to load and test the
 * software's suitability as regards their requirements in conditions enabling
 * the security of their systems and/or data to be ensured and, more generally,
 * to use and operate it in the same conditions as regards security.
 *
 * The fact that you are presently reading this means that you have had
 * knowledge of the CeCILL license and that you accept its terms.
 */
?>

<?php
    $escape = $this->plugin('escapeHtml');
?>

<?php echo $this->pageTitle($this->translate('Solr configuration')); ?>

<div id="page-actions">
    <a class="button" href="<?php echo $this->url('admin/solr/field', ['action' => 'add']); ?>">Add new field</a>
</div>

<h2>Fields</h2>
<?php if (count($fields) > 0): ?>
    <table class="tablesaw">
        <thead>
            <tr>
                <th><?php echo $this->translate('Name (Label)'); ?></th>
                <th><?php echo $this->translate('Property'); ?></th>
                <th><?php echo $this->translate('Indexed'); ?></th>
                <th><?php echo $this->translate('Multi-valued'); ?></th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($fields as $field): ?>
                <tr>
                    <td>
                        <ul class="actions">
                            <li>
                                <?php
                                    echo $field->link('', 'edit', [
                                        'class' => 'o-icon-edit',
                                        'title' => $this->translate('Edit'),
                                    ]);
                                ?>
                            </li>
                            <li>
                                <a href="#"
                                data-sidebar-content-url="<?php echo $escape($field->url('delete-confirm')); ?>"
                                class="o-icon-delete sidebar-content"
                                aria-label="<?php echo $escape($this->translate('Delete')); ?>"
                                title="<?php echo $escape($this->translate('Delete')); ?>"></a>
                            </li>
                        </ul>
                        <?php echo $field->name(); ?> (<?php echo $field->label(); ?>)
                    </td>
                    <td><?php echo $field->property()->term(); ?></td>
                    <td><?php echo $field->isIndexed() ? $this->translate('Yes') : $this->translate('No'); ?></td>
                    <td><?php echo $field->isMultivalued() ? $this->translate('Yes') : $this->translate('No'); ?></td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
<?php endif; ?>

<div class="sidebar">
    <a href="#"
        class="sidebar-close o-icon-close"
        aria-label="<?php echo $escape($this->translate('Close')); ?>"
        title="<?php echo $escape($this->translate('Close')); ?>"></a>
    <div class="sidebar-content"></div>
</div>
